### ISSUE TITLE
Ensure successful building via CI

### ISSUE THREAD

**Issue by feststelltaste** [rmllr/jqa-dashboard#1]
To ensure successful builds, you could add a Travis CI file named `.travis.yml` into the project's root directory and let the project build automatically after every commit via https://travis-ci.org/.

Maybe a build file like this could help (I don't know the exact node.js requirements):

```yaml
language: node_js

node_js:
  - "iojs"
  - "7"

install:
  - "npm install"
  - "npm install graph-app-kit --registry https://neo.jfrog.io/neo/api/npm/npm"
  - "npm run build"
```

This method also integrates nicely with future pull requests where a PR can only be merged if the application builds (and tests run) successfully.
